// config.js - ADDED Debug Logging Flag
require("dotenv").config();

module.exports = {
  /* ▸ Flow endpoints */
  FLOW_ACCESS_NODE: "https://mainnet.onflow.org",
  FLOW_REST_ENDPOINT: "https://rest-mainnet.onflow.org",

  /* ▸ Bot Thresholds (USD) */
  PINNACLESALESBOT_THRESHOLD_PINNACLE: 300,
  FLOWSALESBOT_THRESHOLD_PINNACLE: 300,
  FLOWSALESBOT_THRESHOLD_OTHERS: 300,
  FLOWSALESBOT_THRESHOLD_TOPSHOT: 300,
  FLOWSALESBOT_THRESHOLD_TOPSHOT_PACKS: 300,
  FLOWSALESBOT_THRESHOLD_NFL_PACKS: 300,
  FLOWSALESBOT_THRESHOLD_NFL_ALLDAY: 300,
  FLOWSALESBOT_THRESHOLD_HOTWHEELS: 300,

  /* ▸ Collection on/off switches */
  ENABLED_COLLECTIONS: [
    "TOPSHOT_MOMENT",
    "TOPSHOT_PACK",
    "NFL_PACK",
    "NFL_ALLDAY",
    "HOTWHEELS",
    "PINNACLE",
    "GENERIC_OTHER",
  ],

  DEBUG_LOG_ALL_EVENTS: false,

  /* ▸ Twitter credentials */
  TWITTER_API_KEY: process.env.TWITTER_API_KEY,
  TWITTER_API_SECRET: process.env.TWITTER_API_SECRET,
  PINNACLEPINBOT_ACCESS_TOKEN: process.env.PINNACLEPINBOT_ACCESS_TOKEN,
  PINNACLEPINBOT_ACCESS_SECRET: process.env.PINNACLEPINBOT_ACCESS_SECRET,
  FLOWSALESBOT_ACCESS_TOKEN: process.env.FLOWSALESBOT_ACCESS_TOKEN,
  FLOWSALESBOT_ACCESS_SECRET: process.env.FLOWSALESBOT_ACCESS_SECRET,
};
